<?php
/**
 * Created by PhpStorm.
 * User: appleimac
 * Date: 18/2/26
 * Time: 上午10:52
 */

namespace app\admin\model;


use think\Model;

class Occupation extends Model {

    protected $table = 'occupation';
    protected $pk = 'id';

    protected function initialize() {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}