<?php
/**
 * Created by PhpStorm.
 * User: appleimac
 * Date: 18/2/26
 * Time: 下午3:18
 * 消费类型
 */

namespace app\admin\controller;


use app\admin\base\Base;

class Consumption extends Base {

    protected function _initialize() {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index(){

    }

}