<?php
/**
 * Created by PhpStorm.
 * User: appleimac
 * Date: 18/2/26
 * Time: 下午3:18
 * 消费类型
 */

namespace app\admin\controller;


use app\admin\base\Base;
use think\Request;

class Consumption extends Base {

    protected function _initialize() {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index(){

        $consumptionModel = model('Consumption');
        $list = $consumptionModel->paginate();
        $page = $list->render();

        $this->assign('list', $list);
        $this->assign('page', $page);
        return $this->fetch();
    }

    public function add(){
        $this->post('add');
    }

    public function edit(){
        $this->post('edit');
    }

    public function post($type){

        $id = Request::instance()->get('id');
        $consumptionModel = model('Consumption');
        $info = $consumptionModel->where('id', $id)->find();

        if(Request::instance()->isPost()){

        }
    }

}