<?php
/**
 * Created by PhpStorm.
 * User: appleimac
 * Date: 18/2/25
 * Time: 上午11:23
 */

namespace app\admin\controller;


use app\admin\model\Manager;
use app\admin\base\Base;
use think\Request;

class Login extends Base {

    protected function _initialize() {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index(){

        if($this->checkLoginStatus()){
            $this->success('已登录，直接跳转', $this->ret);
        }

        return $this->fetch();
    }

    public function doLogin(){

        $username = Request::instance()->post('username');
        $password = Request::instance()->post('password');

        if(empty($username) || empty($password)){
            $this->error('用户名或密码不正确', url('login/index'));
        }

        $managerModel = new Manager;
        if($managerModel->doLogin($username, $password)){
            $this->success('登录成功', $this->ret);
        }

        $this->error('登录失败，请重新登录', url('login/index'));
    }

    public function register(){

        return $this->fetch();
    }

    public function doRegister(){

        $userName = Request::instance()->post('username');
        $passWord = Request::instance()->post('password');
        $confirm_password = Request::instance()->post('confirm_password');

        if(empty($userName) || empty($passWord)){
            $this->error('用户名或密码不能为空', url('register'));
        }

        if($passWord != $confirm_password){
            $this->error('两次密码输入不相同', url('register'));
        }

        $info = Manager::scope('userName',$userName)->select();
        if(!empty($info)){
            $this->error('用户名已存在，请重新输入', url('register'));
        }

        Manager::create(['username' => $userName, 'password' => md5($passWord)]);
        $this->success('注册会员成功', url('index/index'));
    }
}