<?php
/**
 * Created by PhpStorm.
 * User: appleimac
 * Date: 18/2/25
 * Time: 上午11:23
 */

namespace app\admin\controller;


use app\admin\base\Base;

class Login extends Base {

    protected function _initialize() {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index(){

        if($this->checkLoginStatus()){
            $this->success('已登录，直接跳转', $this->ret);
        }

        return $this->fetch();
    }

    public function doLogin(){

    }
}