<?php
/**
 * Created by PhpStorm.
 * User: appleimac
 * Date: 18/2/26
 * Time: 下午3:34
 * 职业
 */

namespace app\admin\controller;


use app\admin\base\Base;

class Occupation extends Base {

    protected function _initialize() {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index(){

        $occupation = model('Occupation');
        $list = $occupation->paginate();
        $page = $list->render();
        $this->assign('list', $list);
        $this->assign('page', $page);
        return $this->fetch();
    }

    public function add(){
        $this->post('add');
    }

    public function edit(){
        $this->post('edit');
    }

    private function post($type){

    }
}