<?php
/**
 * Created by PhpStorm.
 * User: appleimac
 * Date: 18/2/25
 * Time: 上午11:16
 */

namespace app\admin\base;


use think\Controller;
use think\Session;

class Base extends Controller {

    protected function _initialize() {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 检测是否登录
     * @return bool
     */
    public function checkLoginStatus(){
        return Session::has('admin') && Session::get('admin.has_login') ? true : false;
    }
}