<?php
/**
 * Created by PhpStorm.
 * User: appleimac
 * Date: 18/2/27
 * Time: 下午2:57
 */

namespace app\index\base;


use think\Controller;
use think\Session;

class Base extends Controller {

    protected function _initialize() {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 检测是否登录
     * @return bool
     */
    protected function checkLoginStatus(){
        return Session::has('login') && Session::get('login.has_login') ? true : false;
    }

    /**
     * 获取会员信息
     * @return array|false|\PDOStatement|string|\think\Model
     */
    protected function getMemberInfo(){
        $uid = Session::get('login.uid');

        $memberModel = model('Member', 'admin/model');
        $member = $memberModel->where('id','=', $uid)->find();
        return $member;
    }
}