<?php
    /**
     * Created by PhpStorm.
     * User: Administrator
     * Date: 2018/2/23
     * Time: 22:08
     */

    namespace app\index\controller;


    use app\index\base\BaseController;
    use think\Session;

    class IndexController extends BaseController {

        public function _initialize() {
            parent::_initialize(); // TODO: Change the autogenerated stub
        }

        public function index(){
            if(!Session::has('login') || !Session::get('hasLogin')){
                $this->error('会员没有登录，请登录后再试.', '__URL__/login',3);
            }



            return $this->fetch();
        }
    }